# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Halftone.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtWidgets, Qt

trigger = False

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 900)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 500, 900))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.image_source = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.image_source.setObjectName("image_source")
        self.verticalLayout.addWidget(self.image_source)
        self.image_change = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.image_change.setObjectName("image_change")
        self.verticalLayout.addWidget(self.image_change)
        # MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_xuanze = QtWidgets.QMenu(self.menubar)
        self.menu_xuanze.setObjectName("menu_xuanze")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        # MainWindow.setMenuBar(self.menubar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionBayer = QtWidgets.QAction(MainWindow)
        self.actionBayer.setObjectName("actionBayer")
        self.actionHalftone = QtWidgets.QAction(MainWindow)
        self.actionHalftone.setObjectName("actionHalftone")
        self.actionScrew = QtWidgets.QAction(MainWindow)
        self.actionScrew.setObjectName("actionScrew")
        self.actionCoarseFatting = QtWidgets.QAction(MainWindow)
        self.actionCoarseFatting.setObjectName("actionCoarseFatting")
        self.action_global = QtWidgets.QAction(MainWindow)
        self.action_global.setObjectName("action_global")
        self.action_local = QtWidgets.QAction(MainWindow)
        self.action_local.setObjectName("action_local")
        self.actionFloydSteinberg = QtWidgets.QAction(MainWindow)
        self.actionFloydSteinberg.setObjectName("actionFloydSteinberg")
        self.actionFloydSteinberg1 = QtWidgets.QAction(MainWindow)
        self.actionFloydSteinberg1.setObjectName("actionFloydSteinberg1")
        self.actionBurkes = QtWidgets.QAction(MainWindow)
        self.actionBurkes.setObjectName("actionBurkes")
        self.actionJarrisJudiceNinke = QtWidgets.QAction(MainWindow)
        self.actionJarrisJudiceNinke.setObjectName("actionJarrisJudiceNinke")
        self.actionStucki = QtWidgets.QAction(MainWindow)
        self.actionStucki.setObjectName("actionStucki")
        self.action_mutil = QtWidgets.QAction(MainWindow)
        self.action_mutil.setObjectName("action_mutil")
        self.menu.addAction(self.actionOpen)
        self.menu_xuanze.addAction(self.actionBayer)
        self.menu_xuanze.addAction(self.actionHalftone)
        self.menu_xuanze.addAction(self.actionScrew)
        self.menu_xuanze.addAction(self.actionCoarseFatting)
        self.menu_2.addAction(self.action_global)
        self.menu_2.addAction(self.action_local)
        self.menu_3.addAction(self.actionFloydSteinberg)
        self.menu_3.addAction(self.actionFloydSteinberg1)
        self.menu_3.addAction(self.actionBurkes)
        self.menu_3.addAction(self.actionJarrisJudiceNinke)
        self.menu_3.addAction(self.actionStucki)
        self.menu_3.addAction(self.action_mutil)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_xuanze.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())

        self.retranslateUi(MainWindow)

        # set signal
        self.actionOpen.triggered.connect(MainWindow.openimage)
        self.actionBayer.triggered.connect(MainWindow.Bayer)
        self.actionHalftone.triggered.connect(MainWindow.Halftone)
        self.actionScrew.triggered.connect(MainWindow.Screw)
        self.actionCoarseFatting.triggered.connect(MainWindow.CoarseFatting)
        self.action_global.triggered.connect(MainWindow.global_dou)
        self.action_local.triggered.connect(MainWindow.local_dou)
        self.actionFloydSteinberg.triggered.connect(MainWindow.Floyd_Steinberg)
        self.actionFloydSteinberg1.triggered.connect(MainWindow.Floyd_Steinberg1)
        self.actionBurkes.triggered.connect(MainWindow.Burkes)
        self.actionJarrisJudiceNinke.triggered.connect(MainWindow.Jarris_Judice_Ninke)
        self.actionStucki.triggered.connect(MainWindow.Stucki)
        self.action_mutil.triggered.connect(MainWindow.mutil)

        # set menu item disable until the image was loaded
        self.actionBayer.setEnabled(trigger)
        self.actionHalftone.setEnabled(trigger)
        self.actionScrew.setEnabled(trigger)
        self.actionCoarseFatting.setEnabled(trigger)
        self.action_global.setEnabled(trigger)
        self.action_local.setEnabled(trigger)
        self.actionFloydSteinberg.setEnabled(trigger)
        self.actionFloydSteinberg1.setEnabled(trigger)
        self.actionBurkes.setEnabled(trigger)
        self.actionJarrisJudiceNinke.setEnabled(trigger)
        self.actionStucki.setEnabled(trigger)
        self.action_mutil.setEnabled(trigger)


        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "颜色抖动实验"))
        self.image_source.setText(_translate("MainWindow", "原图"))
        self.image_source.setAlignment(Qt.Qt.AlignCenter)
        self.image_change.setText(_translate("MainWindow", "目标图"))
        self.image_change.setAlignment(Qt.Qt.AlignCenter)
        self.menu.setTitle(_translate("MainWindow", "操作"))
        self.menu_xuanze.setTitle(_translate("MainWindow", "有序抖动算法"))
        self.menu_2.setTitle(_translate("MainWindow", "无序抖动算法"))
        self.menu_3.setTitle(_translate("MainWindow", "误差扩散算法"))
        self.actionOpen.setText(_translate("MainWindow", "打开图片"))
        self.actionBayer.setText(_translate("MainWindow", "Bayer抖动算法"))
        self.actionHalftone.setText(_translate("MainWindow", "Halftone抖动算法"))
        self.actionScrew.setText(_translate("MainWindow", "Screw抖动算法"))
        self.actionCoarseFatting.setText(_translate("MainWindow", "CoarseFatting抖动算法"))
        self.action_global.setText(_translate("MainWindow", "全局伪随机抖动算法"))
        self.action_local.setText(_translate("MainWindow", "局部伪随机抖动算法"))
        self.actionFloydSteinberg.setText(_translate("MainWindow", "Floyd-Steinberg算法"))
        self.actionFloydSteinberg1.setText(_translate("MainWindow", "蛇形Floyd-Steinberg算法"))
        self.actionBurkes.setText(_translate("MainWindow", "Burkes算法"))
        self.actionJarrisJudiceNinke.setText(_translate("MainWindow", "Jarris-Judice-Ninke算法"))
        self.actionStucki.setText(_translate("MainWindow", "Stucki算法"))
        self.action_mutil.setText(_translate("MainWindow", "多位误差扩散算法"))

